// Generated by CoffeeScript 1.5.0
(function() {
  var ApiClient, default_config, each, extend, fs, request, url, util, _ref;

  url = require('url');

  default_config = require('config');

  util = require('util');

  request = require('request');

  fs = require('fs');

  _ref = require('underscore'), extend = _ref.extend, each = _ref.each;

  ApiClient = (function() {

    ApiClient.create = function(name) {
      var clazz, endpoint_config;
      if (this.config == null) {
        throw "ApiClient not configured";
      }
      endpoint_config = this.config.Endpoints[name];
      clazz = ApiClient;
      if (endpoint_config.type) {
        clazz = this.types[endpoint_config.type];
      }
      return new clazz(endpoint_config);
    };

    ApiClient.types = {
      'ApiClient': ApiClient
    };

    ApiClient.load = function(config, cb, dirname) {
      var _this = this;
      if (dirname == null) {
        dirname = __dirname;
      }
      this.config = config || default_config;
      return fs.readdir(dirname, function(err, files) {
        if (err && cb) {
          cb(err, null);
        }
        each(files, function(file) {
          var full_path;
          full_path = "" + dirname + "/" + file;
          return require(full_path);
        });
        if (cb) {
          return cb(null, _this.config);
        }
      });
    };

    ApiClient.register = function(label, clazz, clazz_name, endpoint_config) {
      var _base;
      this.types || (this.types = {});
      this.types[clazz_name] = clazz;
      this.config || (this.config = {});
      (_base = this.config).Endpoints || (_base.Endpoints = {});
      return this.config.Endpoints[label] = endpoint_config;
    };

    function ApiClient(options) {
      this.host = options.host;
      this.port = options.port;
      this.options = options.options || {};
      if (this.options.protocol && this.options.protocol === 'https') {
        this.port || (this.port = 443);
      } else {
        this.port || (this.port = 80);
      }
      this.request_options = options.request_options;
    }

    ApiClient.prototype.api_path = function() {
      return this.options.base_path || "/";
    };

    ApiClient.prototype.url_config = function(params) {
      if (params == null) {
        params = {};
      }
      return {
        hostname: this.host,
        port: this.port,
        pathname: this.api_path(),
        protocol: this.options.protocol || 'http',
        query: params
      };
    };

    ApiClient.prototype.url = function(params) {
      if (params == null) {
        params = {};
      }
      return url.format(this.url_config(params));
    };

    ApiClient.prototype.get = function(params, headers, cb) {
      var request_opts;
      if (cb == null) {
        cb = void 0;
      }
      request_opts = {
        uri: this.url(params),
        headers: headers,
        method: 'GET'
      };
      if (this.request_options != null) {
        extend(request_opts, this.request_options);
      }
      if (cb) {
        request_opts.callback = cb;
      }
      if (this.options.username && this.options.password) {
        return request.auth(this.options.username, this.options.password).request(request_opts);
      } else {
        return request(request_opts);
      }
    };

    return ApiClient;

  })();

  module.exports = ApiClient;

}).call(this);
