// Generated by CoffeeScript 1.5.0
(function() {
  var ApiClient, config, extend, request, url, util;

  url = require('url');

  config = require('config');

  util = require('util');

  request = require('request');

  extend = require('underscore').extend;

  ApiClient = (function() {

    ApiClient.create = function(name) {
      var clazz, endpoint_config;
      endpoint_config = config.Endpoints[name];
      clazz = ApiClient;
      if (endpoint_config.type) {
        clazz = this.types[endpoint_config.type];
      }
      return new clazz(endpoint_config);
    };

    ApiClient.types = {
      'ApiClient': ApiClient
    };

    function ApiClient(options) {
      this.host = options.host;
      this.port = options.port;
      this.options = options.options || {};
      this.request_options = options.request_options;
    }

    ApiClient.prototype.api_path = function() {
      return this.options.base_path || "/";
    };

    ApiClient.prototype.url_config = function(params) {
      if (params == null) {
        params = {};
      }
      return {
        hostname: this.host,
        port: this.port,
        pathname: this.api_path(),
        protocol: this.options.protocol || 'http',
        query: params
      };
    };

    ApiClient.prototype.url = function(params) {
      if (params == null) {
        params = {};
      }
      return url.format(this.url_config(params));
    };

    ApiClient.prototype.get = function(params, headers, cb) {
      var request_opts;
      if (cb == null) {
        cb = void 0;
      }
      request_opts = {
        uri: this.url(params),
        headers: headers,
        method: 'GET'
      };
      if (this.request_options != null) {
        extend(request_opts, this.request_options);
      }
      if (cb) {
        request_opts.callback = cb;
      }
      if (this.options.username && this.options.password) {
        return request.auth(this.options.username, this.options.password).request(request_opts);
      } else {
        console.log("Making request: " + util.inspect(request_opts));
        return request(request_opts);
      }
    };

    return ApiClient;

  })();

  module.exports = ApiClient;

}).call(this);
