// Generated by CoffeeScript 1.5.0
(function() {
  var ApiClient, VersionedApiClient,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ApiClient = require('./api_client');

  VersionedApiClient = (function(_super) {

    __extends(VersionedApiClient, _super);

    ApiClient.types['VersionedApiClient'] = VersionedApiClient;

    function VersionedApiClient(options) {
      VersionedApiClient.__super__.constructor.call(this, options);
    }

    VersionedApiClient.prototype.api_path = function() {
      var path;
      path = VersionedApiClient.__super__.api_path.apply(this, arguments);
      return "" + path + "/" + this.options.version;
    };

    return VersionedApiClient;

  })(ApiClient);

  module.exports = VersionedApiClient;

}).call(this);
